name: 'po4a Action'
description: 'Generate translations using po4a tool'
branding:
  icon: 'globe'
  color: 'blue'
inputs:
  version:
    description: 'Version of PO4A to use'
    required: true
  config:
    description: 'Path to po4a configuration file'
    required: true
    default: 'po4a.cfg'
  args:
    description: 'Additional arguments to pass to po4a'
    required: false
    default: ''
  language:
    description: 'Specific language to process (e.g., pl, fr, de). Processes all languages if not specified.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Run PO4A in Docker
      shell: bash
      run: |
        if [[ "${{ inputs.version }}" != "0.74" ]]; then
          echo "Starting from 1.3, only po4a version 0.74 or higher is supported. Use 1.3 if you need versions 0.69-0.73."
          exit 1
        fi
        docker pull ghcr.io/qwrtln/po4a-action:${{ inputs.version }}-1.3
        docker run --rm -v ${{ github.workspace }}:/github/workspace -w /github/workspace \
          ghcr.io/qwrtln/po4a-action:${{ inputs.version }}-1.3 \
          ${{ inputs.config }} "${{ inputs.args }}" "${{ inputs.language }}"
